// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {server} from '../models';
import {appicon} from '../models';

export function GetConfig():Promise<config.DeckConfig>;

export function GetNetworkInfo():Promise<server.NetworkInfo>;

export function GetQRCode():Promise<string>;

export function ListInstalledApps():Promise<Array<appicon.AppEntry>>;

export function PickAppIcon():Promise<string>;

export function SaveConfig(arg1:config.DeckConfig):Promise<config.DeckConfig>;

export function SetActiveIP(arg1:string):Promise<server.NetworkInfo>;

export function SetLanguage(arg1:string):Promise<config.DeckConfig>;

export function TestKeypress():Promise<void>;

export function TestOBS(arg1:config.OBSConfig):Promise<void>;
