// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetActiveIP(arg1) {
  return window['go']['main']['App']['SetActiveIP'](arg1);
}

export function TestKeypress() {
  return window['go']['main']['App']['TestKeypress']();
}
